// Author: Abdur Razzak
// Lab: Lab 9
// emit.c implements emit.h
// Resonpsible to emits the MIPS code


#include<string.h>
#include "ast.h"
// #include "emit_private.h"
#include "emit.h"

// PRE: PTR to AST, PTR to FILE
// POST: prints out MIPS code into file, using helper functions
void EMIT_GLOBALS(ASTnode* p, FILE* fp){
 
}

// PRE: PTR to AST, PTR to FILE
// POST: prints out MIPS code into file, using helper functions
void EMIT_STRINGS(ASTnode* p, FILE* fp){
 
}

// PRE: PTR to AST, PTR to FILE
// POST: prints out MIPS code into file, using helper functions
void EMIT(ASTnode* p, FILE* fp){
 if (p== NULL) return;
 if (fp == NULL) return;
 fprintf(fp, "# MIPS CODE GENERATED BY Compliler Class\n\n");
 fprintf(fp, ".data\n\n");
 EMIT_STRINGS(p,fp);
 fprintf(fp, ".align 2\n\n");
 EMIT_GLOBALS(p, fp);
 fprintf(fp, ".text\n\n");
 // EMIT_AST(p, fp);
}