# MIPS CODE GENERATED BY Compliler Class

.data

.align 2
.text

.globl main

f:			# function definition
	move $a1, $sp		# Activation Record Carve out copy SP
	subi $a1 $a1 20		# Activation Record carve out copy size of function
	sw $ra, ($a1)		# Store Return address 
	sw $sp 4($a1)		# Store the old Stack pointer
	move $sp, $a1		# Make SP the current activation record

	sw $t0 8($sp)		# Store value from temp registers into funcion sp + offset pos
	li $a0, 9		# Expression is a constant
	sw $a0 16($sp)		# Assign store RHS temporarily
	move $a0 $sp		# VAR local make a copy of stackpointer
	addi $a0 $a0 12		# VAR local stack pointer plus offset
	lw $a1 16($sp)		# Assign get RHS temporarily
	sw $a1 ($a0)		# Assign the RHS into the memory of LHS


			# Return Statement explicitely mentioned
	move $a0 $sp		# VAR local make a copy of stackpointer
	addi $a0 $a0 12		# VAR local stack pointer plus offset
	lw $a0, ($a0)		# Expression is a VAR
	lw $ra ($sp)		# Load the old environment RA
	lw $sp 4($sp)		# Return from function stack pointer

	jr $ra		# Jump to the caller address
	li $a0, 0		# RETURN has no specified value set to 0
	lw $ra ($sp)		# restore old environment RA
	lw $sp 4($sp)		# Return from function store SP

	jr $ra		# Jump to the caller address
			# END OF FUNCTION f

main:			# function definition
	move $a1, $sp		# Activation Record Carve out copy SP
	subi $a1 $a1 12		# Activation Record carve out copy size of function
	sw $ra, ($a1)		# Store Return address 
	sw $sp 4($a1)		# Store the old Stack pointer
	move $sp, $a1		# Make SP the current activation record

	li $a0, 3		# Expression is a constant
	sw $a0, 8($sp)		# Store arg into memory offset location
	lw $a0, 8($sp)		# Previously stored arg Load into a0
	move $t0, $a0		# Arg to temp
	jal f		# Function Call

	li $v0, 1		# About to print a Number
	syscall		# Call write number


	li $a0, 0		# RETURN has no specified value set to 0
	lw $ra ($sp)		# restore old environment RA
	lw $sp 4($sp)		# Return from function store SP

	li $v0, 10		# Exit from Main, we are done
	syscall		# Exit everything
			# END OF FUNCTION main

